# Generated by Django 3.2.8 on 2021-10-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=128)),
                ('timezone_name', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('expiration_date', models.DateField()),
                ('passcode_mandatory', models.BooleanField()),
                ('dosage', models.CharField(max_length=128)),
                ('max_doses', models.IntegerField()),
                ('form', models.CharField(max_length=128)),
                ('pill_count', models.IntegerField()),
                ('slot_index', models.IntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroHealthApp.config')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroHealthApp.device'),
        ),
    ]
