# Generated by Django 3.2.8 on 2021-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='max_doses',
            new_name='exact_pill_count',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='expiration_date',
            new_name='expires',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='pill_count',
            new_name='max_manual_doses',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='passcode_mandatory',
            new_name='passcode_required',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='slot_index',
            new_name='slot',
        ),
        migrations.AlterField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
